version: '3'
services:
  database:
    image: joshy271/sprintserver:aws
    build: .
    ports:
      - 8080:8080
    environment:
      #- spring.datasource.url=jdbc:mysql://host.docker.internal:3306/sprintdb1
      - spring.datasource.url=jdbc:mysql://finalsprintdb.clg84w8e8l49.us-east-1.rds.amazonaws.com/sprintdb1?enableTLSProtocls=TLSv1.2


#version: '3'
#services:
#  database:
#    image: mysql:latest
#    environment:
#      MYSQL_DATABASE: finalsprint
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Gosthatsit2
#      MYSQL_ROOT_PASSWORD: Gosthatsit2
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#
#  app:
#    image: kaylvigh/sprintserver:latest
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/finalsprint
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=Gosthatsit2
#    depends_on:
#      - database
#
#volumes:
#  db_data:

#version: '3'
#services:
#  database:
#    platform: linux/x86_64
#    image: mysql:5.7
#    ports:
#      - 3306:3306
#    volumes:
#      - ./init.sql:/data/application/init.sql
#    environment:
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: Gosthatsit2
#      MYSQL_DATABASE: finalsprint
#  server:
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      - spring.datasource.url=jdbc:mysql://database:3306/finalsprint
#    command: ["./wait-for.sh", "database:3306", "--", ""]