version: '3'
services:
  database:
    image: joshy271/sprintserver:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/finalsprint